import type { NextPage } from "next";
import Head from "next/head";
import { Map } from "../components/map";
import data from '../data.json';
import { Keyframe } from "../typings";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Map zoom={18} keyframes={data.dev8 as Keyframe[]} />
      </main>
    </>
  );
};

export default Home;
